name: default
css:
  - main.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css
js:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/languages/go.min.js
  - hightlight.js
  - hover.js